denoising_step_list:
- 1000
- 937
- 833
- 625
- 0
warp_denoising_step: false
num_frame_per_block: 3
model_name: /ycji/code/Forcing-KV/pretrained/Wan2.1-T2V-14B
model_kwargs:
  local_attn_size: -1
  timestep_shift: 5.0
  sink_size: 0

dummy_forcing:
  denoise_start: 0 # we compute and perform dummy head pruning from the ARstep@ar_start and denoiseTime@denoise_start
  ar_start: 1
  local_context_length: 1 # the context length for local heads
  num_dummy: 180
  teacache_enabled: false
  teacache_threshold: 0.2


# inference
method: realtime
data_path: prompts/example_prompts.txt
output_folder: videos/realtime_5s
inference_iter: -1
num_output_frames: 21 #21
use_ema: false
seed: 0
num_samples: 1
profile: true
save_with_index: true
global_sink: true
context_noise: 0
resolution: 480

generator_ckpt: /ycji/code/Forcing-KV/pretrained/realtime/krea-realtime-video-14b.safetensors
lora_ckpt: ~

adapter:
  type: "lora"
  rank: 256                    # LoRA rank (typical values: 8, 16, 32, 64)
  alpha: 256                   # LoRA alpha (typically same as rank, but can be different)
  dropout: 0.0                # LoRA dropout rate
  dtype: "bfloat16"          # Data type for LoRA parameters: "bfloat16", "float16", "float32"
  verbose: false              # Whether to print all target module names