denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
num_frame_per_block: 3
model_name: /nfs/ycji_temp/code/DummyForcing/pretrained/Wan2.1-T2V-1.3B
model_kwargs:
  local_attn_size: 12
  timestep_shift: 5.0
  sink_size: 1

forcingkv:
  ar_start: 4
  spatial_context_length: 1 # active in forcingkv, unit is HW
  temporal_context_length: 1 # active in forcingkv, unit is HW (3 == old local_context_length 1)
  dynamic_context_length: 1
  # Teacache
  teacache_enabled: false
  teacache_threshold: 0.2
  # Dynamic KV Cache
  dynamic_temporal_enabled: true
  num_frame_patch: 3
  patch_num: [6,4]
  sim_retention_ratio: 0.33
  # Offline Head Classification
  use_offline_head: true
  offline_head_file: configs_head/forcingkv_heads_longlive_human.json

# inference
method: forcingkv
data_path: prompts/MovieGen/MovieGenVideoBench.txt
extended_prompt_path: prompts/MovieGen/MovieGenVideoBench_extended.txt
prompt_save_truncation: 30 # Otherwise error regarding filename may occur for MovieGen
output_folder: videos/vbench/forcingkv_neibour_continues_longlive_60s_ar4_sink1_spatial1_temporal1_dynamic1_patch3_sim0.33 # TODO add your official sampling dir here
inference_iter: -1
num_output_frames: 240
use_ema: false
seed: 0
num_samples: 5
profile: true
save_with_index: true
global_sink: true
context_noise: 0
resolution: 480

generator_ckpt: /nfs/ycji_temp/code/DummyForcing/pretrained/LongLive-1.3B/models/longlive_base.pt
lora_ckpt: /nfs/ycji_temp/code/DummyForcing/pretrained/LongLive-1.3B/models/lora.pt

adapter:
  type: "lora"
  rank: 256                    # LoRA rank (typical values: 8, 16, 32, 64)
  alpha: 256                   # LoRA alpha (typically same as rank, but can be different)
  dropout: 0.0                # LoRA dropout rate
  dtype: "bfloat16"          # Data type for LoRA parameters: "bfloat16", "float16", "float32"
  verbose: false              # Whether to print all target module names
