denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
num_frame_per_block: 3
model_name: /ycji/code/Forcing-KV/pretrained/Wan2.1-T2V-1.3B
model_kwargs:
  local_attn_size: -1
  timestep_shift: 5.0
  sink_size: 3

forcingkv:
  ar_start: 4 #1
  spatial_context_length: 4 # active in forcingkv, unit is HW
  temporal_context_length: 4 # active in forcingkv, unit is HW (3 == old local_context_length 1)
  dynamic_context_length: 0
  # Teacache
  teacache_enabled: false
  teacache_threshold: 0.2
  # Dynamic KV Cache
  dynamic_temporal_enabled: false
  num_frame_patch: 6
  patch_num: [1,1]
  sim_retention_ratio: 0.33
  # Offline Head Classification
  use_offline_head: true
  offline_head_file: /ycji/code/Forcing-KV/configs_head/forcingkv_heads_selfforcing_naive_sink_3_thr08.json #configs_head/forcingkv_heads_selfforcing_human.json
  quantization_enabled: false

# inference
method: forcingkv
data_path: prompts/MovieGen/MovieGenVideoBench.txt
extended_prompt_path: prompts/MovieGen/MovieGenVideoBench_extended.txt
prompt_save_truncation: 30 # Otherwise error regarding filename may occur for MovieGen
output_folder: videos_new/vbench/streamingllm_self_forcing_30s_ar4_sink3_s4_t4
inference_iter: -1
num_output_frames: 120 #21 # latent num of frames 120
use_ema: true
seed: 0
num_samples: 5
profile: false
save_with_index: true
global_sink: true
context_noise: 0
resolution: 480

generator_ckpt: /ycji/code/Forcing-KV/pretrained/Self-Forcing/checkpoints/self_forcing_dmd.pt
lora_ckpt: ~

adapter:
  type: "lora"
  rank: 256                    # LoRA rank (typical values: 8, 16, 32, 64)
  alpha: 256                   # LoRA alpha (typically same as rank, but can be different)
  dropout: 0.0                # LoRA dropout rate
  dtype: "bfloat16"          # Data type for LoRA parameters: "bfloat16", "float16", "float32"
  verbose: false              # Whether to print all target module names
